package.json
=> Drop publishConf

esbuild.mjs
Replace full minification on library artifacts for better tree shaking support
=> Improve build artifacts

src/components/NostoProduct.ts, src/components/NostoProductCard.ts, src/components/NostoShopify.ts, src/components/NostoSkuOptions.ts, src/components/NostoSwiper.ts, src/utils.ts, test/components/NostoProduct.spec.tsx, test/components/NostoProductCard.spec.tsx
Motivation:
* Better encapsulation, since methods are not anymore exposed via web component object
* Better minification, since function names can be minimized unlike method names
* Better testability?
before
```
-rw-r--r--@ 1 timo.westkamper  staff   9.1K Apr  6 12:02 main.cjs.js
-rw-r--r--@ 1 timo.westkamper  staff    33K Apr  6 12:02 main.cjs.js.map
-rw-r--r--  1 timo.westkamper  staff   8.5K Apr  6 12:02 main.es.bundle.js
-rw-r--r--  1 timo.westkamper  staff    32K Apr  6 12:02 main.es.bundle.js.map
-rw-r--r--@ 1 timo.westkamper  staff   8.5K Apr  6 12:02 main.es.js
-rw-r--r--@ 1 timo.westkamper  staff    32K Apr  6 12:02 main.es.js.map
```
after
```
-rw-r--r--@ 1 timo.westkamper  staff   8.4K Apr  6 13:06 main.cjs.js
-rw-r--r--@ 1 timo.westkamper  staff    33K Apr  6 13:06 …
```
=> Extract methods out

.github/workflows/release.yml, .gitignore, package-lock.json, package.json, src/components/NostoProduct.ts, src/components/NostoProductCard.ts, src/components/NostoShopify.ts, src/components/NostoSkuOptions.ts, src/components/NostoSwiper.ts, src/services/templating.ts
=> Add typedoc docs

.npmrc
=> Drop npmrc

src/components/NostoShopify.ts, src/components/NostoSwiper.ts
=> Improve docs

README.md, dev/templates/swiper/swiper.liquid, src/components/NostoSwiper.ts, test/components/NostoSwiper.spec.tsx, test/library/library.suite.tsx
Simplify NostoSwiper component by getting rid of inner wrapping
=> Use custom element as swiper target element

release.config.js
=> Add missing config file

src/components/NostoProduct.ts, src/components/NostoProduct/store.ts, src/components/NostoSkuOptions.ts
Since the main product image is update the sku prefix is misleading
=> Drop sku prefix

README.md
https://nostosolutions.atlassian.net/browse/CFE-992
=> chore: encode web component statuses

src/components/NostoSwiper.ts, test/components/NostoSwiper.spec.tsx
https://nostosolutions.atlassian.net/browse/CFE-991
=> feat: support for nested swiper usage

commitlint.config.js
=> chore: improve commitlint config

src/components/NostoProduct.ts, src/components/NostoSkuOptions.ts, test/components/NostoSkuOptions.spec.tsx
https://nostosolutions.atlassian.net/browse/CFE-987
=> feat: support ATC on SKU option

README.md, src/components/NostoSwiper.ts, test/components/NostoSwiper.spec.tsx
=> feat: load Swiper CSS

README.md, src/components/NostoProductCard.ts, src/services/templating.ts, test/components/NostoProductCard.spec.tsx, test/library/library.suite.tsx, test/services/templating.spec.tsx
=> fix: use official template script types

README.md, dev/templates/dual/dual-sku.liquid, dev/templates/trio/trio.liquid, src/components/NostoProduct.ts, src/components/NostoProduct/common.ts, src/components/NostoProduct/store.ts, src/components/NostoSkuOptions.ts, src/components/common.ts, test/components/NostoProduct.spec.tsx, test/components/NostoSkuOptions.spec.tsx
BREAKING CHANGE: ns- prefix changed to n-
Align attribute prefixes and add support for price data mapping
https://nostosolutions.atlassian.net/browse/CFE-985
=> fix!: adjust attribute prefixes

README.md, dev/templates/dual/dual-sku.liquid, eslint.config.js, src/components/NostoProduct.ts, src/components/NostoProduct/store.ts, src/components/NostoSkuOptions.ts, src/components/common.ts, test/components/NostoProduct.spec.tsx, test/components/NostoSkuOptions.spec.tsx
Add support for supplying SKU data via nested script element
=> feat: add extended SKU data support

.gitignore, package-lock.json, package.json, vite.config.ts
https://nostosolutions.atlassian.net/browse/CFE-1024
=> chore: add test coverage threshold

README.md, src/components/NostoDynamicCard.ts, src/main.ts, test/components/NostoDynamicCard.spec.ts
https://nostosolutions.atlassian.net/browse/CFE-1043
=> feat: add NostoDynamicCard

src/components/NostoProductCard.ts, test/components/NostoProductCard.spec.tsx, test/library/library.suite.tsx, vite.config.ts
Trim NostoProductCard to core features
=> feat: simplify NostoProductCard

src/components/NostoProduct.ts, src/components/NostoProduct/store.ts
=> chore: extract sku fields

src/components/NostoDynamicCard.ts, test/components/NostoDynamicCard.spec.ts
Loads placeholder content based on cached results
The loading time placeholder styling is left to the component user
=> feat: add support for placeholder content

README.md, src/components/NostoCampaign.ts, src/main.ts, test/components/NostoCampaign.spec.ts
=> fix: expose NostoCampaign

src/components/NostoCampaign.ts, test/components/NostoCampaign.spec.ts
=> fix: add flags to call

package-lock.json, package.json, src/components/NostoCampaign.ts, test/components/NostoCampaign.spec.ts
https://nostosolutions.atlassian.net/browse/CFE-1122
=> CFE-1122: NostoCampaign follow up adjustments

.gitignore, esbuild.mjs, package-lock.json, package.json, src/components/NostoImage.ts, src/components/decorators.ts, src/image/bigcommerce.ts, src/image/shopify.ts, src/image/transform.ts, src/image/types.ts, src/utils.ts, test/image/bigcommerce.spec.ts, test/image/compare-unpic.spec.ts, test/image/shopify.spec.ts, test/image/transform.spec.ts
before
```
-rw-r--r--@ 1 timo.westkamper  staff    23K Jul  5 14:54 main.cjs.js
-rw-r--r--@ 1 timo.westkamper  staff    76K Jul  5 14:54 main.cjs.js.map
-rw-r--r--  1 timo.westkamper  staff    16K Jul  5 14:54 main.es.bundle.js
-rw-r--r--  1 timo.westkamper  staff    73K Jul  5 14:54 main.es.bundle.js.map
-rw-r--r--@ 1 timo.westkamper  staff    22K Jul  5 14:54 main.es.js
-rw-r--r--@ 1 timo.westkamper  staff    75K Jul  5 14:54 main.es.js.map
```
after
```
-rw-r--r--@ 1 timo.westkamper  staff    22K Jul  5 14:52 main.cjs.js
-rw-r--r--@ 1 timo.westkamper  staff    73K Jul  5 14:52 main.cjs.js.map
-rw-r--r--  1 timo.westkamper  staff    16K Jul  5 14:52 main.es.bundle.js
-rw-r--r--  1 timo.westkamper  staff    70K Jul  5 14:52 main.es.bundle.js.map
-rw-r--r--@ 1 timo.westkamper  staff …
```
=> chore: compress code to reduce bundlesize

README.md, src/components/NostoImage/NostoImage.ts
expose NostoImage and remove the alpha flag
=> feat: expose NostoImage

src/components/NostoCampaign/NostoCampaign.ts, src/components/NostoProductCard/NostoProductCard.ts, src/templating/context.ts, src/templating/vue.ts, test/templating/context.spec.ts, test/templating/vue.spec.tsx
Extend the template context with utility functions
=> feat: extend template context

src/templating/context.ts, test/components/NostoProductCard.spec.tsx, test/templating/context.spec.ts
Convert context structure from snake_case to camelCase
=> feat: normalize context to camelCase

src/components/NostoCampaign/NostoCampaign.ts, test/components/NostoCampaign.spec.ts
Use id as alias for placement, since quite a lot of campaigns utilize id scoped styles
=> fix: use id as alias for placement

.github/copilot-instructions.md
=> chore: improve instructions

src/components/NostoCampaign/orchestrator.ts, test/components/NostoCampaign.spec.ts, test/components/orchestrator.spec.ts
Drop flags usage and leave it to the client script to set them in the ev1 handling middlewares
=> fix: drop flags usage

package-lock.json, package.json, src/components/NostoControl/NostoControl.ts, test/components/NostoControl.spec.tsx
=> fix: improve segments access

src/templating/vue.ts, test/templating/vue.spec.tsx
Handle nested template elements in Vue templates in the same way as the official Vue 3
=> fix: handle template elements correctly

.github/copilot-instructions.md
=> chore: define custom element conventions for copilot

.github/copilot-instructions.md
=> chore: add cc conventional commits

package-lock.json, package.json, src/components/NostoSection/NostoSection.ts, src/main.ts, test/components/NostoSection.spec.ts, test/mockNostoRecs.ts, test/msw.setup.ts, vite.config.ts
Custom element for Section Rendering API based recommendation result rendering
=> feat: add NostoSection custom element

src/components/NostoCampaignSection/NostoCampaignSection.ts
=> docs: update NostoCampaignSection docs

test/components/NostoCampaign.spec.tsx, test/components/NostoCampaignSection.spec.tsx, test/components/NostoControl.spec.tsx, test/components/NostoImage.spec.ts, test/components/NostoProduct.spec.tsx, test/components/NostoProductCard.spec.tsx, test/components/skuOptions.spec.tsx, test/setup.ts, vite.config.ts
=> chore: centralize DOM cleanup

test/components/NostoCampaign.spec.tsx, test/components/NostoCampaignSection.spec.tsx, test/components/NostoControl.spec.tsx, test/components/NostoDynamicCard.spec.tsx, test/components/NostoImage.spec.tsx, test/components/NostoProductCard.spec.tsx, test/setup.ts, test/utils/jsx.ts
=> chore: use consistent tsx examples in tests

src/shim.d.ts
=> chore: remove unused declarations

src/components/Image/Image.stories.tsx
=> chore: fix Image storybook story

src/components/SimpleCard/SimpleCard.ts
=> chore: drop unsupported css docs

src/components/SimpleCard/styles.css, src/components/VariantSelector/styles.css
=> chore: simplify styles

src/components/Popup/Popup.ts, src/components/SimpleCard/SimpleCard.ts
=> chore: move top level event listeners to handleEvent
